#!/bin/bash

# Install MINUIT sampler for cobaya
pip install git+https://github.com/xgarrido/cobaya-minuit-sampler.git

# Install CLASS
cd $(mktemp -d)
git clone https://github.com/lesgourg/class_public.git ./class
cd class
make
cd ..
rm -rf $(pwd)
