#!/bin/bash

# Install MINUIT sampler for cobaya
pip install git+https://github.com/xgarrido/cobaya-minuit-sampler.git

# Install CLASS
git clone https://github.com/lesgourg/class_public.git ./class
cd class
make
